INSERT INTO `divisao` (`idDivisao`, `divisao`, `nomeDivisao` , `siglaSei`) VALUES
(14,'DGC','Divisão de Gestão do Cuidado','DGC/GAS1/SUPEX1/SUPEG/COLEX/CH-UFRJ'),
(15,'DENF1','Divisão de Enfermagem 1','DENF1/GAS1/SUPEX1/SUPEG/COLEX/CH-UFRJ'),
(16,'DENF2','Divisão de Enfermagem 2','DENF2/GAS2/SUPEX2/SUPEG/COLEX/CH-UFRJ'),
(17,'DENF3','Divisão de Enfermagem 3','DENF3/GAS3/SUPEX3/SUPEG/COLEX/CH-UFRJ'),
(18,'DADT','Divisão Apoio Diagnóstico e Terapêutico','DADT/GAS1/SUPEX1/SUPEG/COLEX/CH-UFRJ'),
(19,'DCDT1','Divisão de Gestão do Cuidado e Apoio Diagnóstico e Terapêutico 1','DCDT1/GAS2/SUPEX2/SUPEG/COLEX/CH-UFRJ'),
(20,'DCDT2','Divisão de Gestão do Cuidado e Apoio Diagnóstico e Terapêutico 2','DCDT2/GAS3/SUPEX3/SUPEG/COLEX/CH-UFRJ'),
(21,'DAF','Divisão de Administração e Finanças','DAF/SUPAD/SUPEG/COLEX/CH-UFRJ'),
(22,'DLIH','Divisão de Logística e Infraestrutura Hospitalar','DLIH/SUPAD/SUPEG/COLEX/CH-UFRJ'),
(23,'DIVGP','Divisão de Gestão de Pessoas','DIVGP/SUPAD/SUPEG/COLEX/CH-UFRJ'),
(24,'SUPEP','Superintendência de Ensino e Pesquisa','SUPEP/SUPEG/COLEX/CH-UFRJ'),
(25,'SUPEX1','Superintendência-Executiva 1','SUPEX1/SUPEG/COLEX/CH-UFRJ'),
(26,'SUPEX2','Superintendência-Executiva 2','SUPEX2/SUPEG/COLEX/CH-UFRJ'),
(27,'SUPEX3','Superintendência-Executiva 3','SUPEX3/SUPEG/COLEX/CH-UFRJ');
